### PR TITLE
#164082814 Updates README.md 

### PR DESCRIPTION
**Pull request by justMuriithi**
#### What does this PR do?
This PR updates README.md

#### Description of Task to be completed?
* Updates routes for version2

#### How should this be manually tested?
Clone this repo
`$ git clone https://github.com/justMuriithi/politico_api.git`
CD into the project directory
`$ cd politico_api`
Checkout the branch for this PR
`$ git checkout ch-update-readme-164082814 `
Activate the virtual environment
`$ source venv/bin/activate `
Run the app
`$ flask run `

#### What are the relevant pivotal tracker stories?
[#164082814](https://www.pivotaltracker.com/story/show/164082814)

### CODE REVIEW

**Comment by martinMutuma** [comment]
Your Readme looks better

**Review by Quantum-35 — CHANGES_REQUESTED** [review]
Add steps to run your application locally.

**Comment by justMuriithi** [comment]
> Add steps to run your application locally.

Environment setup steps added

**Review by Quantum-35 — APPROVED** [review]
Looks good to merge.

**Pull request merged**
